repos:
  - repo: local
    hooks:
      - id: check_docs
        name: Check all documents are generated
        entry: docs/scripts/pre_comit_check_docs.sh
        language: system
        types: [text]